apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vprzt3g61-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vprzt3g61-dotnet-basic-gitops